// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ocsnotify.proto

package com.asiainfo.cs.common.util;

public final class NotifyPacketProto {
  private NotifyPacketProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface NotifyPacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ocs.NotifyPacket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string chatId = 1;</code>
     */
    String getChatId();
    /**
     * <code>optional string chatId = 1;</code>
     */
    com.google.protobuf.ByteString
        getChatIdBytes();

    /**
     * <code>optional string errMsg = 2;</code>
     */
    String getErrMsg();
    /**
     * <code>optional string errMsg = 2;</code>
     */
    com.google.protobuf.ByteString
        getErrMsgBytes();

    /**
     * <code>optional .ocs.NotifyPacket.NotifyCode notifyCode = 3;</code>
     */
    int getNotifyCodeValue();
    /**
     * <code>optional .ocs.NotifyPacket.NotifyCode notifyCode = 3;</code>
     */
    com.asiainfo.cs.common.util.NotifyPacketProto.NotifyPacket.NotifyCode getNotifyCode();

    /**
     * <code>optional string notifymsg = 4;</code>
     */
    String getNotifymsg();
    /**
     * <code>optional string notifymsg = 4;</code>
     */
    com.google.protobuf.ByteString
        getNotifymsgBytes();

    /**
     * <code>optional string receiver = 5;</code>
     */
    String getReceiver();
    /**
     * <code>optional string receiver = 5;</code>
     */
    com.google.protobuf.ByteString
        getReceiverBytes();

    /**
     * <code>optional string originalUserId = 6;</code>
     */
    String getOriginalUserId();
    /**
     * <code>optional string originalUserId = 6;</code>
     */
    com.google.protobuf.ByteString
        getOriginalUserIdBytes();

    /**
     * <code>optional string result = 7;</code>
     */
    String getResult();
    /**
     * <code>optional string result = 7;</code>
     */
    com.google.protobuf.ByteString
        getResultBytes();

    /**
     * <code>map&lt;string, string&gt; props = 8;</code>
     */
    java.util.Map<String, String>
    getProps();
  }
  /**
   * Protobuf type {@code ocs.NotifyPacket}
   */
  public  static final class NotifyPacket extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ocs.NotifyPacket)
      NotifyPacketOrBuilder {
    // Use NotifyPacket.newBuilder() to construct.
    private NotifyPacket(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private NotifyPacket() {
      chatId_ = "";
      errMsg_ = "";
      notifyCode_ = 0;
      notifymsg_ = "";
      receiver_ = "";
      originalUserId_ = "";
      result_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private NotifyPacket(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              chatId_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              errMsg_ = s;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              notifyCode_ = rawValue;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              notifymsg_ = s;
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              receiver_ = s;
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();

              originalUserId_ = s;
              break;
            }
            case 58: {
              String s = input.readStringRequireUtf8();

              result_ = s;
              break;
            }
            case 66: {
              if (!((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
                props_ = com.google.protobuf.MapField.newMapField(
                    PropsDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000080;
              }
              com.google.protobuf.MapEntry<String, String>
              props = input.readMessage(
                  PropsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              props_.getMutableMap().put(props.getKey(), props.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.asiainfo.cs.common.util.NotifyPacketProto.internal_static_ocs_NotifyPacket_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 8:
          return internalGetProps();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.asiainfo.cs.common.util.NotifyPacketProto.internal_static_ocs_NotifyPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.asiainfo.cs.common.util.NotifyPacketProto.NotifyPacket.class, com.asiainfo.cs.common.util.NotifyPacketProto.NotifyPacket.Builder.class);
    }

    /**
     * Protobuf enum {@code ocs.NotifyPacket.NotifyCode}
     */
    public enum NotifyCode
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>AGENT_NONE = 0;</code>
       */
      AGENT_NONE(0, 0),
      /**
       * <code>AGENT_RING = 100;</code>
       */
      AGENT_RING(1, 100),
      /**
       * <code>AGENT_LONG_NO_ANSWER = 101;</code>
       */
      AGENT_LONG_NO_ANSWER(2, 101),
      /**
       * <code>AGENT_DISTRIBUTE_FAIL = 102;</code>
       */
      AGENT_DISTRIBUTE_FAIL(3, 102),
      /**
       * <code>AGENT_LINK_ESTABLISHED = 103;</code>
       */
      AGENT_LINK_ESTABLISHED(4, 103),
      /**
       * <code>AGENT_LINK_TIMEOUT = 104;</code>
       */
      AGENT_LINK_TIMEOUT(5, 104),
      /**
       * <code>AGENT_CUSTOMER_RELEASE = 105;</code>
       */
      AGENT_CUSTOMER_RELEASE(6, 105),
      /**
       * <code>AGENT_OPPOSITE_TRANS_ROBOT = 106;</code>
       */
      AGENT_OPPOSITE_TRANS_ROBOT(7, 106),
      /**
       * <code>AGENT_CANCLE_RING = 107;</code>
       */
      AGENT_CANCLE_RING(8, 107),
      /**
       * <code>AGENT_FORCE_BUSY = 108;</code>
       */
      AGENT_FORCE_BUSY(9, 108),
      /**
       * <code>AGENT_FORCE_FREE = 109;</code>
       */
      AGENT_FORCE_FREE(10, 109),
      /**
       * <code>AGENT_ACCESS_TIMEOUT = 110;</code>
       */
      AGENT_ACCESS_TIMEOUT(11, 110),
      /**
       * <code>AGENT_LISTEN_CHAT_OPPOSITE = 111;</code>
       */
      AGENT_LISTEN_CHAT_OPPOSITE(12, 111),
      /**
       * <code>AGENT_INNERTRANS_RING = 112;</code>
       */
      AGENT_INNERTRANS_RING(13, 112),
      /**
       * <code>AGENT_TRANS_TIMEOUT = 114;</code>
       */
      AGENT_TRANS_TIMEOUT(14, 114),
      /**
       * <code>AGENT_TRANS_SUCCESS = 115;</code>
       */
      AGENT_TRANS_SUCCESS(15, 115),
      /**
       * <code>AGENT_TRANS_FAIL = 116;</code>
       */
      AGENT_TRANS_FAIL(16, 116),
      /**
       * <code>AGENT_RELEASE = 117;</code>
       */
      AGENT_RELEASE(17, 117),
      /**
       * <code>INSPECTOR_NEWCHAT = 118;</code>
       */
      INSPECTOR_NEWCHAT(18, 118),
      /**
       * <code>INSPECTOR_SIGNOUT = 119;</code>
       */
      INSPECTOR_SIGNOUT(19, 119),
      /**
       * <code>LONG_NO_SENDMSG_TIMEOUT = 120;</code>
       */
      LONG_NO_SENDMSG_TIMEOUT(20, 120),
      /**
       * <code>AGENT_SATE_LIMIT_FAIL = 121;</code>
       */
      AGENT_SATE_LIMIT_FAIL(21, 121),
      /**
       * <code>PASSWORD_VERIFY = 122;</code>
       */
      PASSWORD_VERIFY(22, 122),
      /**
       * <code>AGENT_INFO_PUSH = 123;</code>
       */
      AGENT_INFO_PUSH(23, 123),
      /**
       * <code>AGENT_FORCE_SIGNOUT = 124;</code>
       */
      AGENT_FORCE_SIGNOUT(24, 124),
      /**
       * <code>AGENTANSWER_NOTIFY_INSPECTORS = 125;</code>
       */
      AGENTANSWER_NOTIFY_INSPECTORS(25, 125),
      /**
       * <code>HELPCHAT_RELEASE = 126;</code>
       */
      HELPCHAT_RELEASE(26, 126),
      UNRECOGNIZED(-1, -1),
      ;

      /**
       * <code>AGENT_NONE = 0;</code>
       */
      public static final int AGENT_NONE_VALUE = 0;
      /**
       * <code>AGENT_RING = 100;</code>
       */
      public static final int AGENT_RING_VALUE = 100;
      /**
       * <code>AGENT_LONG_NO_ANSWER = 101;</code>
       */
      public static final int AGENT_LONG_NO_ANSWER_VALUE = 101;
      /**
       * <code>AGENT_DISTRIBUTE_FAIL = 102;</code>
       */
      public static final int AGENT_DISTRIBUTE_FAIL_VALUE = 102;
      /**
       * <code>AGENT_LINK_ESTABLISHED = 103;</code>
       */
      public static final int AGENT_LINK_ESTABLISHED_VALUE = 103;
      /**
       * <code>AGENT_LINK_TIMEOUT = 104;</code>
       */
      public static final int AGENT_LINK_TIMEOUT_VALUE = 104;
      /**
       * <code>AGENT_CUSTOMER_RELEASE = 105;</code>
       */
      public static final int AGENT_CUSTOMER_RELEASE_VALUE = 105;
      /**
       * <code>AGENT_OPPOSITE_TRANS_ROBOT = 106;</code>
       */
      public static final int AGENT_OPPOSITE_TRANS_ROBOT_VALUE = 106;
      /**
       * <code>AGENT_CANCLE_RING = 107;</code>
       */
      public static final int AGENT_CANCLE_RING_VALUE = 107;
      /**
       * <code>AGENT_FORCE_BUSY = 108;</code>
       */
      public static final int AGENT_FORCE_BUSY_VALUE = 108;
      /**
       * <code>AGENT_FORCE_FREE = 109;</code>
       */
      public static final int AGENT_FORCE_FREE_VALUE = 109;
      /**
       * <code>AGENT_ACCESS_TIMEOUT = 110;</code>
       */
      public static final int AGENT_ACCESS_TIMEOUT_VALUE = 110;
      /**
       * <code>AGENT_LISTEN_CHAT_OPPOSITE = 111;</code>
       */
      public static final int AGENT_LISTEN_CHAT_OPPOSITE_VALUE = 111;
      /**
       * <code>AGENT_INNERTRANS_RING = 112;</code>
       */
      public static final int AGENT_INNERTRANS_RING_VALUE = 112;
      /**
       * <code>AGENT_TRANS_TIMEOUT = 114;</code>
       */
      public static final int AGENT_TRANS_TIMEOUT_VALUE = 114;
      /**
       * <code>AGENT_TRANS_SUCCESS = 115;</code>
       */
      public static final int AGENT_TRANS_SUCCESS_VALUE = 115;
      /**
       * <code>AGENT_TRANS_FAIL = 116;</code>
       */
      public static final int AGENT_TRANS_FAIL_VALUE = 116;
      /**
       * <code>AGENT_RELEASE = 117;</code>
       */
      public static final int AGENT_RELEASE_VALUE = 117;
      /**
       * <code>INSPECTOR_NEWCHAT = 118;</code>
       */
      public static final int INSPECTOR_NEWCHAT_VALUE = 118;
      /**
       * <code>INSPECTOR_SIGNOUT = 119;</code>
       */
      public static final int INSPECTOR_SIGNOUT_VALUE = 119;
      /**
       * <code>LONG_NO_SENDMSG_TIMEOUT = 120;</code>
       */
      public static final int LONG_NO_SENDMSG_TIMEOUT_VALUE = 120;
      /**
       * <code>AGENT_SATE_LIMIT_FAIL = 121;</code>
       */
      public static final int AGENT_SATE_LIMIT_FAIL_VALUE = 121;
      /**
       * <code>PASSWORD_VERIFY = 122;</code>
       */
      public static final int PASSWORD_VERIFY_VALUE = 122;
      /**
       * <code>AGENT_INFO_PUSH = 123;</code>
       */
      public static final int AGENT_INFO_PUSH_VALUE = 123;
      /**
       * <code>AGENT_FORCE_SIGNOUT = 124;</code>
       */
      public static final int AGENT_FORCE_SIGNOUT_VALUE = 124;
      /**
       * <code>AGENTANSWER_NOTIFY_INSPECTORS = 125;</code>
       */
      public static final int AGENTANSWER_NOTIFY_INSPECTORS_VALUE = 125;
      /**
       * <code>HELPCHAT_RELEASE = 126;</code>
       */
      public static final int HELPCHAT_RELEASE_VALUE = 126;


      public final int getNumber() {
        if (index == -1) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      public static NotifyCode valueOf(int value) {
        switch (value) {
          case 0: return AGENT_NONE;
          case 100: return AGENT_RING;
          case 101: return AGENT_LONG_NO_ANSWER;
          case 102: return AGENT_DISTRIBUTE_FAIL;
          case 103: return AGENT_LINK_ESTABLISHED;
          case 104: return AGENT_LINK_TIMEOUT;
          case 105: return AGENT_CUSTOMER_RELEASE;
          case 106: return AGENT_OPPOSITE_TRANS_ROBOT;
          case 107: return AGENT_CANCLE_RING;
          case 108: return AGENT_FORCE_BUSY;
          case 109: return AGENT_FORCE_FREE;
          case 110: return AGENT_ACCESS_TIMEOUT;
          case 111: return AGENT_LISTEN_CHAT_OPPOSITE;
          case 112: return AGENT_INNERTRANS_RING;
          case 114: return AGENT_TRANS_TIMEOUT;
          case 115: return AGENT_TRANS_SUCCESS;
          case 116: return AGENT_TRANS_FAIL;
          case 117: return AGENT_RELEASE;
          case 118: return INSPECTOR_NEWCHAT;
          case 119: return INSPECTOR_SIGNOUT;
          case 120: return LONG_NO_SENDMSG_TIMEOUT;
          case 121: return AGENT_SATE_LIMIT_FAIL;
          case 122: return PASSWORD_VERIFY;
          case 123: return AGENT_INFO_PUSH;
          case 124: return AGENT_FORCE_SIGNOUT;
          case 125: return AGENTANSWER_NOTIFY_INSPECTORS;
          case 126: return HELPCHAT_RELEASE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<NotifyCode>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          NotifyCode> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<NotifyCode>() {
              public NotifyCode findValueByNumber(int number) {
                return NotifyCode.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.asiainfo.cs.common.util.NotifyPacketProto.NotifyPacket.getDescriptor().getEnumTypes().get(0);
      }

      private static final NotifyCode[] VALUES = values();

      public static NotifyCode valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private NotifyCode(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:ocs.NotifyPacket.NotifyCode)
    }

    private int bitField0_;
    public static final int CHATID_FIELD_NUMBER = 1;
    private volatile Object chatId_;
    /**
     * <code>optional string chatId = 1;</code>
     */
    public String getChatId() {
      Object ref = chatId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        chatId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string chatId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getChatIdBytes() {
      Object ref = chatId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        chatId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ERRMSG_FIELD_NUMBER = 2;
    private volatile Object errMsg_;
    /**
     * <code>optional string errMsg = 2;</code>
     */
    public String getErrMsg() {
      Object ref = errMsg_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        errMsg_ = s;
        return s;
      }
    }
    /**
     * <code>optional string errMsg = 2;</code>
     */
    public com.google.protobuf.ByteString
        getErrMsgBytes() {
      Object ref = errMsg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        errMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NOTIFYCODE_FIELD_NUMBER = 3;
    private int notifyCode_;
    /**
     * <code>optional .ocs.NotifyPacket.NotifyCode notifyCode = 3;</code>
     */
    public int getNotifyCodeValue() {
      return notifyCode_;
    }
    /**
     * <code>optional .ocs.NotifyPacket.NotifyCode notifyCode = 3;</code>
     */
    public com.asiainfo.cs.common.util.NotifyPacketProto.NotifyPacket.NotifyCode getNotifyCode() {
      com.asiainfo.cs.common.util.NotifyPacketProto.NotifyPacket.NotifyCode result = com.asiainfo.cs.common.util.NotifyPacketProto.NotifyPacket.NotifyCode.valueOf(notifyCode_);
      return result == null ? com.asiainfo.cs.common.util.NotifyPacketProto.NotifyPacket.NotifyCode.UNRECOGNIZED : result;
    }

    public static final int NOTIFYMSG_FIELD_NUMBER = 4;
    private volatile Object notifymsg_;
    /**
     * <code>optional string notifymsg = 4;</code>
     */
    public String getNotifymsg() {
      Object ref = notifymsg_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        notifymsg_ = s;
        return s;
      }
    }
    /**
     * <code>optional string notifymsg = 4;</code>
     */
    public com.google.protobuf.ByteString
        getNotifymsgBytes() {
      Object ref = notifymsg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        notifymsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECEIVER_FIELD_NUMBER = 5;
    private volatile Object receiver_;
    /**
     * <code>optional string receiver = 5;</code>
     */
    public String getReceiver() {
      Object ref = receiver_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        receiver_ = s;
        return s;
      }
    }
    /**
     * <code>optional string receiver = 5;</code>
     */
    public com.google.protobuf.ByteString
        getReceiverBytes() {
      Object ref = receiver_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        receiver_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ORIGINALUSERID_FIELD_NUMBER = 6;
    private volatile Object originalUserId_;
    /**
     * <code>optional string originalUserId = 6;</code>
     */
    public String getOriginalUserId() {
      Object ref = originalUserId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        originalUserId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string originalUserId = 6;</code>
     */
    public com.google.protobuf.ByteString
        getOriginalUserIdBytes() {
      Object ref = originalUserId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        originalUserId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESULT_FIELD_NUMBER = 7;
    private volatile Object result_;
    /**
     * <code>optional string result = 7;</code>
     */
    public String getResult() {
      Object ref = result_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        result_ = s;
        return s;
      }
    }
    /**
     * <code>optional string result = 7;</code>
     */
    public com.google.protobuf.ByteString
        getResultBytes() {
      Object ref = result_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        result_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROPS_FIELD_NUMBER = 8;
    private static final class PropsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          String, String> defaultEntry =
              com.google.protobuf.MapEntry
              .<String, String>newDefaultInstance(
                  com.asiainfo.cs.common.util.NotifyPacketProto.internal_static_ocs_NotifyPacket_PropsEntry_descriptor,
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        String, String> props_;
    private com.google.protobuf.MapField<String, String>
    internalGetProps() {
      if (props_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            PropsDefaultEntryHolder.defaultEntry);
     }
      return props_;
    }
    /**
     * <code>map&lt;string, string&gt; props = 8;</code>
     */

    public java.util.Map<String, String> getProps() {
      return internalGetProps().getMap();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getChatIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, chatId_);
      }
      if (!getErrMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, errMsg_);
      }
      if (notifyCode_ != com.asiainfo.cs.common.util.NotifyPacketProto.NotifyPacket.NotifyCode.AGENT_NONE.getNumber()) {
        output.writeEnum(3, notifyCode_);
      }
      if (!getNotifymsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, notifymsg_);
      }
      if (!getReceiverBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 5, receiver_);
      }
      if (!getOriginalUserIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 6, originalUserId_);
      }
      if (!getResultBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 7, result_);
      }
      for (java.util.Map.Entry<String, String> entry
           : internalGetProps().getMap().entrySet()) {
        com.google.protobuf.MapEntry<String, String>
        props = PropsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        output.writeMessage(8, props);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getChatIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, chatId_);
      }
      if (!getErrMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, errMsg_);
      }
      if (notifyCode_ != com.asiainfo.cs.common.util.NotifyPacketProto.NotifyPacket.NotifyCode.AGENT_NONE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, notifyCode_);
      }
      if (!getNotifymsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, notifymsg_);
      }
      if (!getReceiverBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(5, receiver_);
      }
      if (!getOriginalUserIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(6, originalUserId_);
      }
      if (!getResultBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(7, result_);
      }
      for (java.util.Map.Entry<String, String> entry
           : internalGetProps().getMap().entrySet()) {
        com.google.protobuf.MapEntry<String, String>
        props = PropsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(8, props);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.asiainfo.cs.common.util.NotifyPacketProto.NotifyPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.asiainfo.cs.common.util.NotifyPacketProto.NotifyPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.asiainfo.cs.common.util.NotifyPacketProto.NotifyPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.asiainfo.cs.common.util.NotifyPacketProto.NotifyPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.asiainfo.cs.common.util.NotifyPacketProto.NotifyPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.asiainfo.cs.common.util.NotifyPacketProto.NotifyPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.asiainfo.cs.common.util.NotifyPacketProto.NotifyPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.asiainfo.cs.common.util.NotifyPacketProto.NotifyPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.asiainfo.cs.common.util.NotifyPacketProto.NotifyPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.asiainfo.cs.common.util.NotifyPacketProto.NotifyPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.asiainfo.cs.common.util.NotifyPacketProto.NotifyPacket prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ocs.NotifyPacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ocs.NotifyPacket)
        com.asiainfo.cs.common.util.NotifyPacketProto.NotifyPacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.asiainfo.cs.common.util.NotifyPacketProto.internal_static_ocs_NotifyPacket_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 8:
            return internalGetProps();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 8:
            return internalGetMutableProps();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.asiainfo.cs.common.util.NotifyPacketProto.internal_static_ocs_NotifyPacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.asiainfo.cs.common.util.NotifyPacketProto.NotifyPacket.class, com.asiainfo.cs.common.util.NotifyPacketProto.NotifyPacket.Builder.class);
      }

      // Construct using com.asiainfo.cs.NotifyPacketProto.NotifyPacket.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        chatId_ = "";

        errMsg_ = "";

        notifyCode_ = 0;

        notifymsg_ = "";

        receiver_ = "";

        originalUserId_ = "";

        result_ = "";

        internalGetMutableProps().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.asiainfo.cs.common.util.NotifyPacketProto.internal_static_ocs_NotifyPacket_descriptor;
      }

      public com.asiainfo.cs.common.util.NotifyPacketProto.NotifyPacket getDefaultInstanceForType() {
        return com.asiainfo.cs.common.util.NotifyPacketProto.NotifyPacket.getDefaultInstance();
      }

      public com.asiainfo.cs.common.util.NotifyPacketProto.NotifyPacket build() {
        com.asiainfo.cs.common.util.NotifyPacketProto.NotifyPacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.asiainfo.cs.common.util.NotifyPacketProto.NotifyPacket buildPartial() {
        com.asiainfo.cs.common.util.NotifyPacketProto.NotifyPacket result = new com.asiainfo.cs.common.util.NotifyPacketProto.NotifyPacket(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.chatId_ = chatId_;
        result.errMsg_ = errMsg_;
        result.notifyCode_ = notifyCode_;
        result.notifymsg_ = notifymsg_;
        result.receiver_ = receiver_;
        result.originalUserId_ = originalUserId_;
        result.result_ = result_;
        result.props_ = internalGetProps();
        result.props_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.asiainfo.cs.common.util.NotifyPacketProto.NotifyPacket) {
          return mergeFrom((com.asiainfo.cs.common.util.NotifyPacketProto.NotifyPacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.asiainfo.cs.common.util.NotifyPacketProto.NotifyPacket other) {
        if (other == com.asiainfo.cs.common.util.NotifyPacketProto.NotifyPacket.getDefaultInstance()) return this;
        if (!other.getChatId().isEmpty()) {
          chatId_ = other.chatId_;
          onChanged();
        }
        if (!other.getErrMsg().isEmpty()) {
          errMsg_ = other.errMsg_;
          onChanged();
        }
        if (other.notifyCode_ != 0) {
          setNotifyCodeValue(other.getNotifyCodeValue());
        }
        if (!other.getNotifymsg().isEmpty()) {
          notifymsg_ = other.notifymsg_;
          onChanged();
        }
        if (!other.getReceiver().isEmpty()) {
          receiver_ = other.receiver_;
          onChanged();
        }
        if (!other.getOriginalUserId().isEmpty()) {
          originalUserId_ = other.originalUserId_;
          onChanged();
        }
        if (!other.getResult().isEmpty()) {
          result_ = other.result_;
          onChanged();
        }
        internalGetMutableProps().mergeFrom(
            other.internalGetProps());
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.asiainfo.cs.common.util.NotifyPacketProto.NotifyPacket parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.asiainfo.cs.common.util.NotifyPacketProto.NotifyPacket) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object chatId_ = "";
      /**
       * <code>optional string chatId = 1;</code>
       */
      public String getChatId() {
        Object ref = chatId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          chatId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string chatId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getChatIdBytes() {
        Object ref = chatId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          chatId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string chatId = 1;</code>
       */
      public Builder setChatId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        chatId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string chatId = 1;</code>
       */
      public Builder clearChatId() {

        chatId_ = getDefaultInstance().getChatId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string chatId = 1;</code>
       */
      public Builder setChatIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        chatId_ = value;
        onChanged();
        return this;
      }

      private Object errMsg_ = "";
      /**
       * <code>optional string errMsg = 2;</code>
       */
      public String getErrMsg() {
        Object ref = errMsg_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          errMsg_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string errMsg = 2;</code>
       */
      public com.google.protobuf.ByteString
          getErrMsgBytes() {
        Object ref = errMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          errMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string errMsg = 2;</code>
       */
      public Builder setErrMsg(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        errMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string errMsg = 2;</code>
       */
      public Builder clearErrMsg() {

        errMsg_ = getDefaultInstance().getErrMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string errMsg = 2;</code>
       */
      public Builder setErrMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        errMsg_ = value;
        onChanged();
        return this;
      }

      private int notifyCode_ = 0;
      /**
       * <code>optional .ocs.NotifyPacket.NotifyCode notifyCode = 3;</code>
       */
      public int getNotifyCodeValue() {
        return notifyCode_;
      }
      /**
       * <code>optional .ocs.NotifyPacket.NotifyCode notifyCode = 3;</code>
       */
      public Builder setNotifyCodeValue(int value) {
        notifyCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .ocs.NotifyPacket.NotifyCode notifyCode = 3;</code>
       */
      public com.asiainfo.cs.common.util.NotifyPacketProto.NotifyPacket.NotifyCode getNotifyCode() {
        com.asiainfo.cs.common.util.NotifyPacketProto.NotifyPacket.NotifyCode result = com.asiainfo.cs.common.util.NotifyPacketProto.NotifyPacket.NotifyCode.valueOf(notifyCode_);
        return result == null ? com.asiainfo.cs.common.util.NotifyPacketProto.NotifyPacket.NotifyCode.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .ocs.NotifyPacket.NotifyCode notifyCode = 3;</code>
       */
      public Builder setNotifyCode(com.asiainfo.cs.common.util.NotifyPacketProto.NotifyPacket.NotifyCode value) {
        if (value == null) {
          throw new NullPointerException();
        }

        notifyCode_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .ocs.NotifyPacket.NotifyCode notifyCode = 3;</code>
       */
      public Builder clearNotifyCode() {

        notifyCode_ = 0;
        onChanged();
        return this;
      }

      private Object notifymsg_ = "";
      /**
       * <code>optional string notifymsg = 4;</code>
       */
      public String getNotifymsg() {
        Object ref = notifymsg_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          notifymsg_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string notifymsg = 4;</code>
       */
      public com.google.protobuf.ByteString
          getNotifymsgBytes() {
        Object ref = notifymsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          notifymsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string notifymsg = 4;</code>
       */
      public Builder setNotifymsg(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        notifymsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string notifymsg = 4;</code>
       */
      public Builder clearNotifymsg() {

        notifymsg_ = getDefaultInstance().getNotifymsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string notifymsg = 4;</code>
       */
      public Builder setNotifymsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        notifymsg_ = value;
        onChanged();
        return this;
      }

      private Object receiver_ = "";
      /**
       * <code>optional string receiver = 5;</code>
       */
      public String getReceiver() {
        Object ref = receiver_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          receiver_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string receiver = 5;</code>
       */
      public com.google.protobuf.ByteString
          getReceiverBytes() {
        Object ref = receiver_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          receiver_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string receiver = 5;</code>
       */
      public Builder setReceiver(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        receiver_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string receiver = 5;</code>
       */
      public Builder clearReceiver() {

        receiver_ = getDefaultInstance().getReceiver();
        onChanged();
        return this;
      }
      /**
       * <code>optional string receiver = 5;</code>
       */
      public Builder setReceiverBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        receiver_ = value;
        onChanged();
        return this;
      }

      private Object originalUserId_ = "";
      /**
       * <code>optional string originalUserId = 6;</code>
       */
      public String getOriginalUserId() {
        Object ref = originalUserId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          originalUserId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string originalUserId = 6;</code>
       */
      public com.google.protobuf.ByteString
          getOriginalUserIdBytes() {
        Object ref = originalUserId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          originalUserId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string originalUserId = 6;</code>
       */
      public Builder setOriginalUserId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        originalUserId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string originalUserId = 6;</code>
       */
      public Builder clearOriginalUserId() {

        originalUserId_ = getDefaultInstance().getOriginalUserId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string originalUserId = 6;</code>
       */
      public Builder setOriginalUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        originalUserId_ = value;
        onChanged();
        return this;
      }

      private Object result_ = "";
      /**
       * <code>optional string result = 7;</code>
       */
      public String getResult() {
        Object ref = result_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          result_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string result = 7;</code>
       */
      public com.google.protobuf.ByteString
          getResultBytes() {
        Object ref = result_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          result_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string result = 7;</code>
       */
      public Builder setResult(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string result = 7;</code>
       */
      public Builder clearResult() {

        result_ = getDefaultInstance().getResult();
        onChanged();
        return this;
      }
      /**
       * <code>optional string result = 7;</code>
       */
      public Builder setResultBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        result_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          String, String> props_;
      private com.google.protobuf.MapField<String, String>
      internalGetProps() {
        if (props_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              PropsDefaultEntryHolder.defaultEntry);
       }
        return props_;
      }
      private com.google.protobuf.MapField<String, String>
      internalGetMutableProps() {
        onChanged();;
        if (props_ == null) {
          props_ = com.google.protobuf.MapField.newMapField(
              PropsDefaultEntryHolder.defaultEntry);
        }
        if (!props_.isMutable()) {
          props_ = props_.copy();
        }
        return props_;
      }
      /**
       * <code>map&lt;string, string&gt; props = 8;</code>
       */
      public java.util.Map<String, String> getProps() {
        return internalGetProps().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; props = 8;</code>
       */
      public java.util.Map<String, String>
      getMutableProps() {
        return internalGetMutableProps().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; props = 8;</code>
       */
      public Builder putAllProps(
          java.util.Map<String, String> values) {
        getMutableProps().putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:ocs.NotifyPacket)
    }

    // @@protoc_insertion_point(class_scope:ocs.NotifyPacket)
    private static final com.asiainfo.cs.common.util.NotifyPacketProto.NotifyPacket DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.asiainfo.cs.common.util.NotifyPacketProto.NotifyPacket();
    }

    public static com.asiainfo.cs.common.util.NotifyPacketProto.NotifyPacket getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NotifyPacket>
        PARSER = new com.google.protobuf.AbstractParser<NotifyPacket>() {
      public NotifyPacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new NotifyPacket(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<NotifyPacket> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<NotifyPacket> getParserForType() {
      return PARSER;
    }

    public com.asiainfo.cs.common.util.NotifyPacketProto.NotifyPacket getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ocs_NotifyPacket_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ocs_NotifyPacket_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ocs_NotifyPacket_PropsEntry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ocs_NotifyPacket_PropsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017ocsnotify.proto\022\003ocs\"\261\007\n\014NotifyPacket\022" +
      "\016\n\006chatId\030\001 \001(\t\022\016\n\006errMsg\030\002 \001(\t\0220\n\nnotif" +
      "yCode\030\003 \001(\0162\034.ocs.NotifyPacket.NotifyCod" +
      "e\022\021\n\tnotifymsg\030\004 \001(\t\022\020\n\010receiver\030\005 \001(\t\022\026" +
      "\n\016originalUserId\030\006 \001(\t\022\016\n\006result\030\007 \001(\t\022+" +
      "\n\005props\030\010 \003(\0132\034.ocs.NotifyPacket.PropsEn" +
      "try\032,\n\nPropsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030" +
      "\002 \001(\t:\0028\001\"\246\005\n\nNotifyCode\022\016\n\nAGENT_NONE\020\000" +
      "\022\016\n\nAGENT_RING\020d\022\030\n\024AGENT_LONG_NO_ANSWER" +
      "\020e\022\031\n\025AGENT_DISTRIBUTE_FAIL\020f\022\032\n\026AGENT_L",
      "INK_ESTABLISHED\020g\022\026\n\022AGENT_LINK_TIMEOUT\020" +
      "h\022\032\n\026AGENT_CUSTOMER_RELEASE\020i\022\036\n\032AGENT_O" +
      "PPOSITE_TRANS_ROBOT\020j\022\025\n\021AGENT_CANCLE_RI" +
      "NG\020k\022\024\n\020AGENT_FORCE_BUSY\020l\022\024\n\020AGENT_FORC" +
      "E_FREE\020m\022\030\n\024AGENT_ACCESS_TIMEOUT\020n\022\036\n\032AG" +
      "ENT_LISTEN_CHAT_OPPOSITE\020o\022\031\n\025AGENT_INNE" +
      "RTRANS_RING\020p\022\027\n\023AGENT_TRANS_TIMEOUT\020r\022\027" +
      "\n\023AGENT_TRANS_SUCCESS\020s\022\024\n\020AGENT_TRANS_F" +
      "AIL\020t\022\021\n\rAGENT_RELEASE\020u\022\025\n\021INSPECTOR_NE" +
      "WCHAT\020v\022\025\n\021INSPECTOR_SIGNOUT\020w\022\033\n\027LONG_N",
      "O_SENDMSG_TIMEOUT\020x\022\031\n\025AGENT_SATE_LIMIT_" +
      "FAIL\020y\022\023\n\017PASSWORD_VERIFY\020z\022\023\n\017AGENT_INF" +
      "O_PUSH\020{\022\027\n\023AGENT_FORCE_SIGNOUT\020|\022!\n\035AGE" +
      "NTANSWER_NOTIFY_INSPECTORS\020}\022\024\n\020HELPCHAT" +
      "_RELEASE\020~B$\n\017com.asiainfo.csB\021NotifyPac" +
      "ketProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ocs_NotifyPacket_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ocs_NotifyPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ocs_NotifyPacket_descriptor,
        new String[] { "ChatId", "ErrMsg", "NotifyCode", "Notifymsg", "Receiver", "OriginalUserId", "Result", "Props", });
    internal_static_ocs_NotifyPacket_PropsEntry_descriptor =
      internal_static_ocs_NotifyPacket_descriptor.getNestedTypes().get(0);
    internal_static_ocs_NotifyPacket_PropsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ocs_NotifyPacket_PropsEntry_descriptor,
        new String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
